name: preset-common-image-build

description: "A reusable workflow for building preset images"

inputs:
  weights_dir:
    description: "The directory for weights"
    required: true
  branch_name:
    description: "Branch name"
    required: true
  image_name:
    description: "Image name"
    required: true
  image_tag:
    description: "Image tag"
    required: true
  acr_name:
    description: "ACR name"
    required: true
  acr_username:
    description: "ACR username"
    required: true
  acr_password:
    description: "ACR password"
    required: true
  model_name:
    description: "Model name"
    required: true
  model_type:
    description: "Model type"
    required: true
  model_version:
    description: "Model version"
    required: true
  model_runtime:
    description: "Model runtime"
    required: true
  hf_username:
    description: "HuggingFace Username"
    required: true
  hf_token:
    description: "HuggingFace Token"
    required: true
  runs_on:
    description: "The runner to use"
    required: true
  ghcr_username:
    description: "GitHub username or organization name for GHCR"
    required: true
  ghcr_token:
    description: "GitHub token for pushing to GHCR"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: true
        fetch-depth: 0

    - name: Install Azure CLI latest
      run: |
        if ! which az > /dev/null; then
          echo "Azure CLI not found. Installing..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        else
          echo "Azure CLI already installed."
        fi
      shell: bash

    - name: Check Available Disk Space
      run: |
        echo "Initial disk usage:"
        df -h

        # Check Docker-related disk usage after cleanup
        echo "Docker-related disk usage after cleanup:"
        docker system df

        # Check final disk usage
        echo "Final disk usage:"
        df -h
      shell: bash

    - name: Install Hugging Face CLI
      run: |
        echo "Installing Hugging Face CLI..."
        if ! pip install huggingface-hub; then
          pip install huggingface-hub --break-system-packages
        fi
      shell: bash

    - name: Install ORAS CLI
      run: |
        if ! command -v oras &> /dev/null; then
          echo "Installing ORAS CLI..."
          ORAS_VERSION=$(curl -s https://api.github.com/repos/oras-project/oras/releases/latest | grep 'tag_name' | cut -d\" -f4)
          curl -LO "https://github.com/oras-project/oras/releases/download/${ORAS_VERSION}/oras_${ORAS_VERSION#v}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf "oras_${ORAS_VERSION#v}_linux_amd64.tar.gz" -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras-install "oras_${ORAS_VERSION#v}_linux_amd64.tar.gz"
        else
          echo "ORAS CLI already installed."
        fi
        oras version
      shell: bash

    - name: Set up Docker Buildx
      run: |
        # Define a builder name variable that includes the current file name
        BUILDER_NAME="img-builder"
        echo "Using builder name: $BUILDER_NAME"

        # Check if the builder instance already exists
        if ! docker buildx inspect $BUILDER_NAME &>/dev/null; then
          echo "Creating new Docker Buildx instance '$BUILDER_NAME'..."
          docker buildx create --name=$BUILDER_NAME --driver=docker-container --use --bootstrap --driver-opt image=mcr.microsoft.com/oss/v2/moby/buildkit:v0.20.2
        else
          echo "Docker Buildx instance '$BUILDER_NAME' already exists, using it..."
          docker buildx use $BUILDER_NAME
        fi

        # Verify the builder is working
        docker buildx inspect --bootstrap
      shell: bash

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ inputs.ghcr_token }}" | docker login ghcr.io -u ${{ inputs.ghcr_username }} --password-stdin
      shell: bash

    - name: Check if Image exists in target registries
      id: check_test_image
      run: |
        ACR_NAME=${{ inputs.acr_name }}
        GHCR_USERNAME=${{ inputs.ghcr_username }}
        IMAGE_NAME=${{ inputs.image_name }}
        TAG=${{ inputs.image_tag }}

        # Check ACR (use original logic - always build for now)
        echo "IMAGE_EXISTS=false" >> $GITHUB_OUTPUT
        
        # Optional: Check GHCR existence (currently disabled to ensure builds)
        # if docker buildx imagetools inspect ghcr.io/$GHCR_USERNAME/$IMAGE_NAME:$TAG > /dev/null 2>&1; then
        #   echo "Image ghcr.io/$GHCR_USERNAME/$IMAGE_NAME:$TAG exists in GHCR."
        #   echo "IMAGE_EXISTS=true" >> $GITHUB_OUTPUT
        # fi
      shell: bash

    - name: Build model image
      if: steps.check_test_image.outputs.IMAGE_EXISTS == 'false' && inputs.model_name != 'base'
      run: |
        PR_BRANCH=${{ inputs.branch_name }}
        ACR_NAME=${{ inputs.acr_name }}
        ACR_USERNAME=${{ inputs.acr_username }}
        ACR_PASSWORD=${{ inputs.acr_password }}
        IMAGE_NAME=${{ inputs.image_name }}
        MODEL_NAME=${{ inputs.model_name }}
        MODEL_TYPE=${{ inputs.model_type }}
        MODEL_VERSION_URL=${{ inputs.model_version }}
        MODEL_RUNTIME=${{ inputs.model_runtime }}
        MODEL_TAG=${{ inputs.image_tag }}
        WEIGHTS_DIR=${{ inputs.weights_dir }}
        HF_USERNAME=${{ inputs.hf_username }}
        HF_TOKEN=${{ inputs.hf_token }}
        GHCR_USERNAME=${{ inputs.ghcr_username }}

        # Login to ACR registry
        echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin

        # Use shared script to build and push OCI artifact to both ACR and GHCR
        # First push to ACR (original)
        docker/presets/models/tfs/build_oci_artifact.sh \
          "$MODEL_VERSION_URL" \
          "$IMAGE_NAME" \
          "$ACR_NAME.azurecr.io" \
          "$MODEL_TAG" \
          "$HF_TOKEN"
        
        # Then push to GHCR (new)
        docker/presets/models/tfs/build_oci_artifact.sh \
          "$MODEL_VERSION_URL" \
          "$GHCR_USERNAME/$IMAGE_NAME" \
          "ghcr.io" \
          "$MODEL_TAG" \
          "$HF_TOKEN"

      shell: bash

    - name: Build Base Model
      if: steps.check_test_image.outputs.IMAGE_EXISTS == 'false' && inputs.model_name == 'base'
      run: |
        PR_BRANCH=${{ inputs.branch_name }}
        ACR_NAME=${{ inputs.acr_name }}
        ACR_USERNAME=${{ inputs.acr_username }}
        ACR_PASSWORD=${{ inputs.acr_password }}
        IMAGE_NAME=${{ inputs.image_name }}
        MODEL_NAME=${{ inputs.model_name }}
        MODEL_TYPE=${{ inputs.model_type }}
        MODEL_VERSION=${{ inputs.model_version }}
        MODEL_RUNTIME=${{ inputs.model_runtime }}
        MODEL_TAG=${{ inputs.image_tag }}
        WEIGHTS_DIR=${{ inputs.weights_dir }}
        HF_USERNAME=${{ inputs.hf_username }}
        HF_TOKEN=${{ inputs.hf_token }}
        GHCR_USERNAME=${{ inputs.ghcr_username }}

        # Login to ACR registry
        echo $ACR_PASSWORD | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin

        # Build and push to both registries
        docker buildx build \
          --builder img-builder \
          --build-arg VERSION=$MODEL_TAG \
          --build-arg MODEL_TYPE=$MODEL_TYPE \
          --output type=image,name=$ACR_NAME.azurecr.io/$IMAGE_NAME:$MODEL_TAG,push=true,compression=zstd \
          --output type=image,name=ghcr.io/$GHCR_USERNAME/$IMAGE_NAME:$MODEL_TAG,push=true,compression=zstd \
          -f ./docker/presets/models/tfs/Dockerfile .
      shell: bash